Add s3 prefix and fix get size
sdv-dev/SDGym pull request #185
Opened 2023-01-19 17:47 UTC by katxiao

Resolves #184 
Resolves #183 
Resolves #182

2023-01-20 15:22 UTC, pvk-developer approved these changes

2023-01-20 15:22 UTC, pvk-developer commented on sdgym/utils.py
> +        seen = set()
Just a nit, could we add a break line ?

2023-01-20 19:05 UTC, amontanez24 requested changes

2023-01-20 19:05 UTC, amontanez24 commented on sdgym/datasets.py
> +    bucket_name = bucket[len(S3_PREFIX):] if bucket.startswith(S3_PREFIX) else bucket
minor but we can make this a function since you use it later too. Like a `get_bucket_name_from_path` of something

2023-01-23 19:25 UTC, amontanez24 approved these changes
Thanks for addressing! :shipit:

2023-01-23 21:45 UTC, merged